remote_theme: 42bv/fortytwo
title: '@42/ui'
baseurl: /ui/
description: 'Components as used within 42 products'
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: 'assets/img'
    values:
      image: true
