remote_theme: 42bv/fortytwo
title: '@42/ui'
baseurl: /ui/
description: 'Components as used within 42 products'
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: 'assets/img'
    values:
      image: true
links:
  - name: 'View on Github'
    icon: 'https://unpkg.com/simple-icons@latest/icons/github.svg'
    href: 'https://github.com/42BV/ui'
  - name: 'Storybook'
    icon: 'https://unpkg.com/simple-icons@latest/icons/storybook.svg'
    href: 'https://42bv.github.io/ui/storybook'
